
[package]
name = "ripgrep_all"
description = "rga: ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc."
license = "AGPL-3.0-or-later"
readme = "README.md"
version = "0.9.7-alpha.0"
repository = "https://github.com/phiresky/ripgrep-all"
homepage = "https://github.com/phiresky/ripgrep-all"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
exclude = [
    "exampledir/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree_magic = { package = "tree_magic_mini", version = "1.0.0" }
regex = "1.3.9"
rkv = "0.10.4"
path-clean = "0.1.0"
bincode = "1.2.1"
serde = { version = "1.0.111", features = ["derive"] }
zstd = "0.5.2"
lazy_static = "1.4.0"
serde_json = "1.0.53"
zip = "0.5.5"
crossbeam = "0.7.3"
clap = { version = "2.33.1", features = ["wrap_help"] }
log = "0.4.8"
env_logger = "0.7.1"
xz2 = "0.1.6"
flate2 = "1.0.14"
bzip2 = "0.3.3"
tar = "0.4.28"
chrono = "0.4.11"
encoding_rs = "0.8.23"
encoding_rs_io = "0.1.7"
rusqlite = { version = "0.23.1", features = ["vtab", "bundled"] }
size_format = "1.0.2"
structopt = "0.3.14"
paste = "0.1.16"
tempfile = "3.1.0"
glob = "0.3.0"
anyhow = "1.0.31"
schemars = {version = "0.8.0-alpha-2", features = ["preserve_order"]}
directories-next = "1.0.1"
derive_more = "0.99.7"
pretty-bytes = "0.2.2"
memchr = "2.3.3"
crossbeam-channel = "0.4.2"
dyn-clone = "1.0.1"
dyn-clonable = "0.9.0"
